Implement benchmarker of external commands
cookpad/dokumi pull request #11
Opened 2016-10-17 08:55 UTC by giginet

I implement benchmarker for the execution time of external commands.

## Usage

```sh
bin/archive --benchmarker_export_path=execute_time.json
```

2016-10-17 09:04 UTC, giginet commented on lib/dokumi/support/benchmark.rb
> +        @data = {}
I think, it should be `Array` rather than `Hash`.
Because it stores ordering.

2016-10-21 05:43 UTC, vincentisambart requested changes

2016-10-21 05:43 UTC, vincentisambart commented on lib/dokumi/command.rb
> +      self.export_benchmark_report(environment_options)
I don't see why you would want to use `self.`.

2016-10-21 05:43 UTC, vincentisambart commented on lib/dokumi/support/shell.rb
> +          Support.benchmarker.measure(args.join(' ')) do
Why making an `args.join` here?

2016-10-21 05:43 UTC, vincentisambart commented on lib/dokumi/support/benchmark.rb
> +      end
Wouldn't the following make things clearer?
```ruby
def measure(args, &block)
  command = args.map {|arg| arg.to_s.shellescape }
  start_time = Time.now
  tms = Benchmark.measure(command, &block)
  data << ExecutionLog.new(command, tms, start_time)
end
```

2016-10-21 05:43 UTC, vincentisambart commented on lib/dokumi/support/benchmark.rb
> +      @benchmarker = Benchmarker.new
`@benchmarker ||= Benchmarker.new` ?

2016-10-21 06:14 UTC, giginet commented on lib/dokumi/command.rb
> +      self.export_benchmark_report(environment_options)
Because of unification with above call.
I'll remove `self` from both lines.

2016-10-21 06:16 UTC, giginet commented on lib/dokumi/support/shell.rb
> +          Support.benchmarker.measure(args.join(' ')) do
I got.
`measure` should receive a list of arguments, and join them in this method.

2016-10-21 06:26 UTC, giginet commented
Thank you for reviewing.
I've fixed.

2016-10-21 07:40 UTC, kazu-matsu commented on lib/dokumi/support/benchmark.rb
> +        { command: command,
How about adding a new line ?

```ruby
{
  command: command,
...
```

2016-10-21 07:44 UTC, giginet commented on lib/dokumi/support/benchmark.rb
> +        { command: command,
According to our style guide, I think it should not break new lines here.

https://github.com/cookpad/styleguide/blob/master/ruby.en.md#hashes

2016-10-21 07:46 UTC, kazu-matsu commented on lib/dokumi/support/benchmark.rb
> +        { command: command,
oh, I mistook. A new line is required other case :p

2016-10-25 00:11 UTC, vincentisambart requested changes

2016-10-25 00:11 UTC, vincentisambart commented on lib/dokumi/support/benchmark.rb
> +        Support.logger.info "#{filename} is exported"
s/is/has been

2016-10-25 00:11 UTC, vincentisambart commented on lib/dokumi/command.rb
> +      export_benchmark_report(environment_options)
重複してるよ

2016-10-25 00:11 UTC, vincentisambart commented on lib/dokumi/support/benchmark.rb
> +          JSON.dump(data.map(&:to_hash), file)
全部が1行に出るのはエディターで読みづらくない？

2016-10-25 00:11 UTC, vincentisambart commented
ちゃんと実行してみた？

2016-10-25 00:14 UTC, giginet commented on lib/dokumi/support/benchmark.rb
> +          JSON.dump(data.map(&:to_hash), file)
`cat *.json | jq .`してた
`pretty_genarate`試してみます

2016-10-25 00:14 UTC, giginet commented on lib/dokumi/command.rb
> +      export_benchmark_report(environment_options)
😨

2016-10-26 01:58 UTC, vincentisambart approved these changes
LGTM

2016-10-26 01:58 UTC, vincentisambart commented on lib/dokumi/support/benchmark.rb
> +        { command: command,
I think what Kazuaki was suggesting looked better, but if it's the official style... :(

2016-10-26 02:01 UTC, merged