Lint support
cookpad/dokumi pull request #12
Opened 2016-11-11 02:23 UTC by tatsuhama

add Android Lint

2016-11-11 03:11 UTC, giginet requested changes
Thank you for your contribution 😄 

I commented some issues.

2016-11-11 03:11 UTC, giginet commented on test/lint.rb
> +    issues = Dokumi::Command.review("github.com", "tatsuhama", "DokumiLint", 1, skip_comment_creation: true, build_script: build_script)
Could you also send PR to cookpad/dokumi-test and use it?

https://github.com/cookpad/dokumi-test/pulls

2016-11-11 03:11 UTC, giginet commented on test/lint.rb
> +      assert_equal :lint, issue[:tool]
According to our styleguide you should use `{}` syntax on the statement in one line.
https://github.com/cookpad/styleguide/blob/master/ruby.en.md#method-calls

`issues.each { |issue| assert_equal :lint, issue[:tool] }`

2016-11-11 03:11 UTC, giginet commented on lib/dokumi/tool/android/lint.rb
> +                {
According to our styleguide, you should not break lines here.

https://github.com/cookpad/styleguide/blob/master/ruby.en.md#hashes

2016-11-11 05:17 UTC, tatsuhama commented
@giginet 
I fixed your comments.
Please check my commits.

2016-11-11 05:31 UTC, giginet requested changes

2016-11-11 05:31 UTC, giginet commented on lib/dokumi/tool/android/lint.rb
> +              report.xpath("//issue").map do |issue| {
I'm sorry confusing you 🙇 , linebreak is needed here.
I meant

```ruby
report.xpath("//issue").map do |issue|
  { description: issue.attribute("message").to_s,
    file_path: issue.xpath("location/@file").to_s,
    line: issue.xpath("location/@line").to_s.to_i,
    type: issue.attribute("severity").to_s == "Error" ? :error : :warning,
  }
end
```
opening bracket of hashes requires to be same line with first element.

2016-11-11 05:40 UTC, tatsuhama commented on lib/dokumi/tool/android/lint.rb
> +              report.xpath("//issue").map do |issue| {
@giginet 
I fixed.
Please check my commit.
https://github.com/cookpad/dokumi/pull/12/commits/68746516b9c4930f55840318683198e9f06a7c92

2016-11-11 11:21 UTC, giginet approved these changes

2016-11-17 02:29 UTC, giginet commented
I'm sorry. I made you wait.
I asked an Android engineer to check this PR, therefore it seems to LGTM.
I'll merge.

Thank you contribution 🎉

2016-11-17 02:30 UTC, merged